"""Add quiz options

Revision ID: 45f6d5ed4386
Revises: 63acfc095c12
Create Date: 2026-05-25 19:25:10.845666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f6d5ed4386'
down_revision = '63acfc095c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_selected_option', sa.String(length=10), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quiz_correct_answer', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quiz_correct_answer')
        batch_op.drop_column('quiz_options')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_column('quiz_selected_option')

    # ### end Alembic commands ###
