"""Add student_code and ParentStudentLink

Revision ID: 5720bef9cc8d
Revises: 6ba1266e70cd
Create Date: 2026-05-26 08:44:22.829962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5720bef9cc8d'
down_revision = '6ba1266e70cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('live_start_time')

    # ### end Alembic commands ###
